name: Regenerate
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  regenerate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Delete all files except README
        run: |
          shopt -s extglob
          rm -rf !(README.md|.git|additional.txt)
          shopt -u extglob
      - name: Optimize space of ubuntu installation
        run: |
          curl -fsSL https://raw.githubusercontent.com/kou/arrow/e49d8ae15583ceff03237571569099a6ad62be32/ci/scripts/util_free_space.sh | bash
          docker system prune -af || true
          docker builder prune -af || true
          df -h
      - name: Fetch reapack URLS
        run: |
          curl -o repos.txt https://reapack.com/repos.txt
          echo additional.txt >> repos.txt
      - name: Generate
        run: |
          nix run github:silvarc141/reapkgs -- -gpr -i repos.txt -o .
      - name: Clean Up
        run: |
          rm -rf repos.txt
      - name: Lock
        run: |
          df -h
          nix flake lock
      - name: Commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git diff --quiet HEAD || (git commit -am "flake regeneration $(date +'%Y-%m-%d')" && git push)
