name: Regenerate
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
jobs:
  regenerate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@v4
      - name: Delete all files except README
        run: |
          shopt -s extglob
          rm -rf !(README.md|.git)
          shopt -u extglob
      - name: Generate
        run: nix run github:silvarc141/reapkgs -- -gprq -j 2 -o .
      - name: Commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -A
          git diff --quiet HEAD || (git commit -am "Regenerate $(date +'%Y-%m-%d')" && git push)
